export const PROVINCE_ITALIANE = [
  'AG', 'AL', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AT', 'AV', 'BA', 'BG', 'BI', 'BL', 'BN', 'BO', 
  'BR', 'BS', 'BT', 'BZ', 'CA', 'CB', 'CE', 'CH', 'CL', 'CN', 'CO', 'CR', 'CS', 'CT', 'CZ',
  'EN', 'FC', 'FE', 'FG', 'FI', 'FM', 'FR', 'GE', 'GO', 'GR', 'IM', 'IS', 'KR', 'LC', 'LE',
  'LI', 'LO', 'LT', 'LU', 'MB', 'MC', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NA', 'NO', 'NU',
  'OR', 'PA', 'PC', 'PD', 'PE', 'PG', 'PI', 'PN', 'PO', 'PR', 'PT', 'PU', 'PV', 'PZ', 'RA',
  'RC', 'RE', 'RG', 'RI', 'RM', 'RN', 'RO', 'SA', 'SI', 'SO', 'SP', 'SR', 'SS', 'SU', 'SV',
  'TA', 'TE', 'TN', 'TO', 'TP', 'TR', 'TS', 'TV', 'UD', 'VA', 'VB', 'VC', 'VE', 'VI', 'VR',
  'VT', 'VV'
];

export const CITTA_ITALIANE = [
  // Principali città per regione
  { nome: 'Roma', provincia: 'RM', regione: 'Lazio' },
  { nome: 'Milano', provincia: 'MI', regione: 'Lombardia' },
  { nome: 'Napoli', provincia: 'NA', regione: 'Campania' },
  { nome: 'Torino', provincia: 'TO', regione: 'Piemonte' },
  { nome: 'Palermo', provincia: 'PA', regione: 'Sicilia' },
  { nome: 'Genova', provincia: 'GE', regione: 'Liguria' },
  { nome: 'Bologna', provincia: 'BO', regione: 'Emilia-Romagna' },
  { nome: 'Firenze', provincia: 'FI', regione: 'Toscana' },
  { nome: 'Bari', provincia: 'BA', regione: 'Puglia' },
  { nome: 'Catania', provincia: 'CT', regione: 'Sicilia' },
  { nome: 'Venezia', provincia: 'VE', regione: 'Veneto' },
  { nome: 'Verona', provincia: 'VR', regione: 'Veneto' },
  { nome: 'Messina', provincia: 'ME', regione: 'Sicilia' },
  { nome: 'Padova', provincia: 'PD', regione: 'Veneto' },
  { nome: 'Trieste', provincia: 'TS', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Brescia', provincia: 'BS', regione: 'Lombardia' },
  { nome: 'Parma', provincia: 'PR', regione: 'Emilia-Romagna' },
  { nome: 'Taranto', provincia: 'TA', regione: 'Puglia' },
  { nome: 'Prato', provincia: 'PO', regione: 'Toscana' },
  { nome: 'Modena', provincia: 'MO', regione: 'Emilia-Romagna' },
  { nome: 'Reggio Calabria', provincia: 'RC', regione: 'Calabria' },
  { nome: 'Reggio Emilia', provincia: 'RE', regione: 'Emilia-Romagna' },
  { nome: 'Perugia', provincia: 'PG', regione: 'Umbria' },
  { nome: 'Ravenna', provincia: 'RA', regione: 'Emilia-Romagna' },
  { nome: 'Livorno', provincia: 'LI', regione: 'Toscana' },
  { nome: 'Cagliari', provincia: 'CA', regione: 'Sardegna' },
  { nome: 'Foggia', provincia: 'FG', regione: 'Puglia' },
  { nome: 'Rimini', provincia: 'RN', regione: 'Emilia-Romagna' },
  { nome: 'Salerno', provincia: 'SA', regione: 'Campania' },
  { nome: 'Ferrara', provincia: 'FE', regione: 'Emilia-Romagna' },
  { nome: 'Sassari', provincia: 'SS', regione: 'Sardegna' },
  { nome: 'Monza', provincia: 'MB', regione: 'Lombardia' },
  { nome: 'Bergamo', provincia: 'BG', regione: 'Lombardia' },
  { nome: 'Pescara', provincia: 'PE', regione: 'Abruzzo' },
  { nome: 'Trento', provincia: 'TN', regione: 'Trentino-Alto Adige' },
  { nome: 'Vicenza', provincia: 'VI', regione: 'Veneto' },
  { nome: 'Terni', provincia: 'TR', regione: 'Umbria' },
  { nome: 'Bolzano', provincia: 'BZ', regione: 'Trentino-Alto Adige' },
  { nome: 'Piacenza', provincia: 'PC', regione: 'Emilia-Romagna' },
  { nome: 'Ancona', provincia: 'AN', regione: 'Marche' },
  { nome: 'Andria', provincia: 'BT', regione: 'Puglia' },
  { nome: 'Arezzo', provincia: 'AR', regione: 'Toscana' },
  { nome: 'Udine', provincia: 'UD', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Cesena', provincia: 'FC', regione: 'Emilia-Romagna' },
  { nome: 'Lecce', provincia: 'LE', regione: 'Puglia' },
  { nome: 'Pesaro', provincia: 'PU', regione: 'Marche' },
  { nome: 'Barletta', provincia: 'BT', regione: 'Puglia' },
  { nome: 'Alessandria', provincia: 'AL', regione: 'Piemonte' },
  { nome: 'La Spezia', provincia: 'SP', regione: 'Liguria' },
  { nome: 'Pisa', provincia: 'PI', regione: 'Toscana' },
  { nome: 'Catanzaro', provincia: 'CZ', regione: 'Calabria' },
  { nome: 'Pistoia', provincia: 'PT', regione: 'Toscana' },
  { nome: 'Brindisi', provincia: 'BR', regione: 'Puglia' },
  { nome: 'Como', provincia: 'CO', regione: 'Lombardia' },
  { nome: 'Varese', provincia: 'VA', regione: 'Lombardia' },
  { nome: 'Treviso', provincia: 'TV', regione: 'Veneto' },
  { nome: 'Caserta', provincia: 'CE', regione: 'Campania' },
  { nome: 'Asti', provincia: 'AT', regione: 'Piemonte' },
  { nome: 'Cremona', provincia: 'CR', regione: 'Lombardia' },
  { nome: 'Novara', provincia: 'NO', regione: 'Piemonte' },
  { nome: 'Ragusa', provincia: 'RG', regione: 'Sicilia' },
  { nome: 'Siracusa', provincia: 'SR', regione: 'Sicilia' },
  { nome: 'Latina', provincia: 'LT', regione: 'Lazio' },
  { nome: 'Viterbo', provincia: 'VT', regione: 'Lazio' },
  { nome: 'Benevento', provincia: 'BN', regione: 'Campania' },
  { nome: 'Avellino', provincia: 'AV', regione: 'Campania' },
  { nome: "L'Aquila", provincia: 'AQ', regione: 'Abruzzo' },
  { nome: 'Frosinone', provincia: 'FR', regione: 'Lazio' },
  { nome: 'Cuneo', provincia: 'CN', regione: 'Piemonte' },
  { nome: 'Pordenone', provincia: 'PN', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Siena', provincia: 'SI', regione: 'Toscana' },
  { nome: 'Grosseto', provincia: 'GR', regione: 'Toscana' },
  { nome: 'Forlì', provincia: 'FC', regione: 'Emilia-Romagna' },
  { nome: 'Trapani', provincia: 'TP', regione: 'Sicilia' },
  { nome: 'Lucca', provincia: 'LU', regione: 'Toscana' },
  { nome: 'Rovigo', provincia: 'RO', regione: 'Veneto' },
  { nome: 'Pavia', provincia: 'PV', regione: 'Lombardia' },
  { nome: 'Savona', provincia: 'SV', regione: 'Liguria' },
  { nome: 'Vercelli', provincia: 'VC', regione: 'Piemonte' },
  { nome: 'Agrigento', provincia: 'AG', regione: 'Sicilia' },
  { nome: 'Caltanissetta', provincia: 'CL', regione: 'Sicilia' },
  { nome: 'Potenza', provincia: 'PZ', regione: 'Basilicata' },
  { nome: 'Matera', provincia: 'MT', regione: 'Basilicata' },
  { nome: 'Cosenza', provincia: 'CS', regione: 'Calabria' },
  { nome: 'Chieti', provincia: 'CH', regione: 'Abruzzo' },
  { nome: 'Teramo', provincia: 'TE', regione: 'Abruzzo' },
  { nome: 'Imperia', provincia: 'IM', regione: 'Liguria' },
  { nome: 'Biella', provincia: 'BI', regione: 'Piemonte' },
  { nome: 'Belluno', provincia: 'BL', regione: 'Veneto' },
  { nome: 'Gorizia', provincia: 'GO', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Massa', provincia: 'MS', regione: 'Toscana' },
  { nome: 'Carrara', provincia: 'MS', regione: 'Toscana' },
  { nome: 'Lodi', provincia: 'LO', regione: 'Lombardia' },
  { nome: 'Mantova', provincia: 'MN', regione: 'Lombardia' },
  { nome: 'Sondrio', provincia: 'SO', regione: 'Lombardia' },
  { nome: 'Lecco', provincia: 'LC', regione: 'Lombardia' },
  { nome: 'Enna', provincia: 'EN', regione: 'Sicilia' },
  { nome: 'Rieti', provincia: 'RI', regione: 'Lazio' },
  { nome: 'Vibo Valentia', provincia: 'VV', regione: 'Calabria' },
  { nome: 'Crotone', provincia: 'KR', regione: 'Calabria' },
  { nome: 'Isernia', provincia: 'IS', regione: 'Molise' },
  { nome: 'Campobasso', provincia: 'CB', regione: 'Molise' },
  { nome: 'Macerata', provincia: 'MC', regione: 'Marche' },
  { nome: 'Ascoli Piceno', provincia: 'AP', regione: 'Marche' },
  { nome: 'Fermo', provincia: 'FM', regione: 'Marche' },
  { nome: 'Verbania', provincia: 'VB', regione: 'Piemonte' },
  { nome: 'Oristano', provincia: 'OR', regione: 'Sardegna' },
  { nome: 'Nuoro', provincia: 'NU', regione: 'Sardegna' },
  { nome: 'Sud Sardegna', provincia: 'SU', regione: 'Sardegna' },
  { nome: 'Aosta', provincia: 'AO', regione: 'Valle d\'Aosta' },
];
